# Generated by Django 2.1.3 on 2018-12-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
    ]
